### ISSUE TITLE
Google Code error on go get project

### ISSUE THREAD

**Issue by jleclanche** [solarkennedy/tfa_auth_dump#1]
```
$ go get github.com/solarkennedy/tfa_auth_dump
# cd .; hg clone -U https://code.google.com/p/rsc /home/adys/src/go/src/code.google.com/p/rsc
abort: HTTP Error 404: Not Found
package code.google.com/p/rsc/qr: exit status 255
```

**Comment by solarkennedy** [comment]
:(

**Comment by solarkennedy** [comment]
Well there is this:
https://github.com/rsc/rsc/tree/master/qr

But it is still full of references to the old import path. Maybe he will take a PR, or maybe I'll take the code and start maintaining it or something?

**Comment by jleclanche** [comment]
You could keep the qr functionality separate from the project and just generate URLs. That way someone might do something like `for url in $(tfa_auth_dump ...); do qrencode $url; done`.

**Comment by solarkennedy** [comment]
Hmm. Not a bad suggestion :)

**Comment by solarkennedy** [comment]
Instead I fixed this using an alternative library.
